### ISSUE TITLE
NRM

### ISSUE THREAD

**Issue by Bidhan-ghimire** [nilforooshan/ggroups#1]
High values of NRM while calculating a dataset with 6460 number of individuals.

**Comment by nilforooshan** [comment]
Hi, would you please explain more? If it is OK, you may share the data via email (you can find it in my profile).

**Comment by Bidhan-ghimire** [comment]
Hy,

The issue is resolved. Actually, there was an error interpreting the NRM
displayed on the screen from my side. I assumed column number to be the
values of components of NRM matix. I am sorry to have bothered you.

Regards,
Bidhan

**Comment by nilforooshan** [comment]
No worries, I'm glad everything is working well.

**Comment by Bidhan-ghimire** [comment]
ped4 = data.frame(ID=c(3,4,6,5),SIRE=c(0,3,4,0),DAM=c(0,0,5,0))
ped4
gghead(ped4)
##replacing 0 with NA doesn't make it work either, not useful.
Can you tell me reason for the same ?
