### ISSUE TITLE
Issue with function gghead

### ISSUE THREAD

**Issue by Bidhan-ghimire** [nilforooshan/ggroups#2]
ped4 = data.frame(ID=c(3,4,6,5),SIRE=c(0,3,4,0),DAM=c(0,0,5,0))
ped4
gghead(ped4)
##replacing 0 with NA doesn't make it work either, not useful.
Can you tell me reason for the same ?

Output:
  ID  SIRE DAM
1 0      0     0
2 0      0     0
3 3      0     0
4 4      3     0
6 5      0     0
5 6      4     5

**Comment by nilforooshan** [comment]
Hi, function "gghead" is for working with genetic groups. You would need to replace zeros in ped4 with genetic groups. Please see the example in the manual. Please read the [manual](https://cran.r-project.org/web/packages/ggroups/ggroups.pdf) before writing an issue. Thank you
